id: I56887B74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:33:11+00:00'
last_modified: '2022-06-08T07:03:51.366324+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB25429
  title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་པཎ་ཆེན་ཤནྟི་པ་བློ་གྲོས་རྒྱལ་མཚན་གྱིས་མཛད་པ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFF9:
      image_group_id: I1PD36299
      title: ''
      total_pages: 778
      order: 1
      base_file: FFF9.txt
    '7781':
      image_group_id: I1PD36300
      title: ''
      total_pages: 794
      order: 2
      base_file: 7781.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
