id: P006817
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2DB25429
  title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་པཎ་ཆེན་ཤནྟི་པ་བློ་གྲོས་རྒྱལ་མཚན་གྱིས་མཛད་པ་།
  author: ''
  volumes:
    dd4785a571594d6a991266909d019efe:
      image_group_id: I1PD36299
      title: ''
      volume_number: 1
      total_pages: 778
      base_file: v001.txt
    dbf7a46376dc4af098a7205128af36db:
      image_group_id: I1PD36300
      title: ''
      volume_number: 2
      total_pages: 794
      base_file: v002.txt
